Ghost                                    ( FunctionEngine.CheatManager.Ghost )
DebugAI                                  ( FunctionEngine.CheatManager.DebugAI )
DebugPause                               ( FunctionEngine.CheatManager.DebugPause )
ListDynamicActors                        ( FunctionEngine.CheatManager.ListDynamicActors )
FreezeFrame                              ( FunctionEngine.CheatManager.FreezeFrame )
WriteToLog                               ( FunctionEngine.CheatManager.WriteToLog )
