## Credits: Sunbeam

Ghost                                    ( FunctionEngine.CheatManager.Ghost )
DebugAI                                  ( FunctionEngine.CheatManager.DebugAI )
DebugPause                               ( FunctionEngine.CheatManager.DebugPause )
ListDynamicActors                        ( FunctionEngine.CheatManager.ListDynamicActors )
FreezeFrame                              ( FunctionEngine.CheatManager.FreezeFrame )
WriteToLog                               ( FunctionEngine.CheatManager.WriteToLog )
KillViewedActor                          ( FunctionEngine.CheatManager.KillViewedActor )
Teleport                                 ( FunctionEngine.CheatManager.Teleport )
ChangeSize                               ( FunctionEngine.CheatManager.ChangeSize )
EndPath                                  ( FunctionEngine.CheatManager.EndPath )
Amphibious                               ( FunctionEngine.CheatManager.Amphibious )
Fly                                      ( FunctionEngine.CheatManager.Fly )
Walk                                     ( FunctionEngine.CheatManager.Walk )
AllAmmo                                  ( FunctionEngine.CheatManager.AllAmmo )
God                                      ( FunctionEngine.CheatManager.God )
Slomo                                    ( FunctionEngine.CheatManager.Slomo )
SetJumpZ                                 ( FunctionEngine.CheatManager.SetJumpZ )
SetGravity                               ( FunctionEngine.CheatManager.SetGravity )
SetSpeed                                 ( FunctionEngine.CheatManager.SetSpeed )
KillAll                                  ( FunctionEngine.CheatManager.KillAll )
